name: canary
on:
  push:
    branches:
      - master

jobs:
  canary:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        check-latest: trues

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --ignore-scripts --frozen-lockfile --ignore-engines

    - name: Build typescript code
      id: yarn-build
      run: yarn build

    - name: publish canary version
      id: publish
      run: |
        PKG_NAME=$(node -p "require('./package.json').name")
        echo "PKG_NAME: ${PKG_NAME}"
        CANARY_VERSION=$(yarn info $PKG_NAME dist-tags.canary | sed -n 2p | sed s/undefined//)
        LATEST_VERSION=$(yarn info $PKG_NAME dist-tags.latest | sed -n 2p | sed s/undefined//)
        echo "CANARY_VERSION: ${CANARY_VERSION}, LATEST_VERSION: ${LATEST_VERSION}"
        npm i semver --no-save --no-package-lock --ignore-scripts --no-audit
        VERSION=$(node_modules/.bin/semver -i prerelease --preid canary $(node -e "console.log(require('semver').gt('$CANARY_VERSION' || '0.0.0', '$LATEST_VERSION' || '0.0.0') ? '$CANARY_VERSION' : '$LATEST_VERSION')"))
        echo "VERSION: ${VERSION}"
        cat ~/.npmrc
        cat ~/.yarnrc
        yarn publish --new-version $VERSION -tag canary --no-git-tag-version --no-commit-hooks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
